# Generated by Django 2.1.1 on 2018-09-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='detail',
            field=models.CharField(max_length=1000, verbose_name='详情'),
        ),
    ]
