platform :ios, '8.0'
use_frameworks!

target 'music' do
  pod 'MJRefresh', '3.1.0'
  pod 'MBProgressHUD', '1.1.0'
  pod 'SDCycleScrollView', '1.75'
  # pod 'Realm', '3.7.6'
# 动画
  pod 'pop', '1.0.10'

  pod 'JZNavigationExtension', '1.5.0'
# 网络
  pod 'AFNetworking', '3.1.0'
# 解析
  pod 'MJExtension', '3.0.0'
# 友盟分享、第三方登录
  pod 'UMCCommon'
  pod 'UMCSecurityPlugins'
# 集成微信(精简版0.2M)
  pod 'UMCShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(精简版0.5M)
  pod 'UMCShare/Social/ReducedQQ'
# 集成新浪微博(精简版1M)
  pod 'UMCShare/Social/ReducedSina'

end
